MVE: Implement Binary glTF 2.0 mesh export
simonfuhrmann/mve pull request #578
Opened 2024-12-21 17:38 UTC by andre-schulz

Hi,
this PR implements a Binary glTF 2.0 (aka GLB) exporter. The code was implemented according to the glTF 2.0 spec available at:
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html

The implementation was tested by validating the resulting GLB with the official glTF Validator:
https://github.khronos.org/glTF-Validator/

Fixes #571

2024-12-21 18:04 UTC, andre-schulz commented
The macOS 12 CI pipeline failed because the runner has been deprecated since 3rd December 2024. I've opened a PR to fix this, see PR #579.

2024-12-22 01:05 UTC, simonfuhrmann requested changes

2024-12-22 14:05 UTC, andre-schulz commented on libs/mve/mesh_io_glb.cc
> +    std::size_t const verts_size_bytes = verts.size() * sizeof(verts[0]);
Are you sure that this is unsafe? Correct me if I'm wrong but I believe `sizeof` is evaluated at compile-time in C++ which means that `verts[0]` is never dereferenced at runtime. Quote from [C++14 draft § 5.3.3/1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf#subsection.5.3.3):
> The `sizeof` operator yields the number of bytes in the object representation of its operand. The operand is
either an expression, which is an unevaluated operand (Clause 5), or a parenthesized _type-id_.

Quote from [C++14 draft § 5/8](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf#chapter.5):
> In some contexts, unevaluated operands appear (5.2.8, 5.3.3, 5.3.7, 7.1.6.2). An unevaluated operand is not
evaluated. An unevaluated operand is considered a full-expression.

Quote from [C++14 draft § 5.3.3/6](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf#subsection.5.3.3):
> The result of `sizeof` and `sizeof...` is a constant of type `std::size_t`.

2024-12-23 19:29 UTC, simonfuhrmann commented on libs/mve/mesh_io_glb.cc
> +    std::size_t const verts_size_bytes = verts.size() * sizeof(verts[0]);
> Correct me if I'm wrong

Haha, I think you just disproved me sufficiently.

> `sizeof` is evaluated at compile-time

Yes, that makes a lot of sense.

2024-12-23 19:30 UTC, merged